---

project_dir: "{{ playbook_dir }}/.."
local_dbdumps_dir: "{{ project_dir }}/dbdumps"
overwrite_local_db: false


project_name: trivago2015


django_settings: config.settings.production
user: "{{ project_name }}"
database_name: "{{ project_name }}"
user_dir: "/home/{{ user }}"
log_root: "{{ user_dir }}/logs"
run_root: "{{ user_dir }}/run"
data_root: "{{ user_dir }}/data"
webapp_dir: "{{ user_dir }}/{{ project_name }}_webapp"
#django_dir: "{{ webapp_dir }}/{{ project_name }}"
django_dir: "{{ webapp_dir }}"
virtualenv_dir: "{{ user_dir }}/.virtualenvs/{{ project_name }}"
static_dir: "{{ django_dir }}/staticfiles"


#server_name: j212975.servers.jiffybox.net
server_name: www.metoo.link


postgres_dumps_dir: /tmp/pgdumps
postgres_effective_cache_size: 248MB
postgres_shared_buffers: 128MB

django_webapp_log_dir: "{{ log_root }}/django"

nginx_maintenance_dir: "/etc/nginx/maintenance"
nginx_proxy_set_header_port: ""

dev_requirements: no
vagrant: no

gunicorn_num_workers: 5
gunicorn_max_requests: 1000
gunicorn_user: "{{ user }}"


DJANGO_AWS_ACCESS_KEY_ID: "aws_access_key_id"
DJANGO_AWS_SECRET_ACCESS_KEY: "aws_secret_access_key"
DJANGO_AWS_STORAGE_BUCKET_NAME: "aws_storage_bucket_name"
SENDGRID_USERNAME: "ephes"
SENDGRID_PASSWORD: "kaeph6Re"
